### PR TITLE
Fix create_comm in ThebeManager

### LINKED ISSUE #302: Pan/zoom button on bqplot does not work
**Describe the bug**
When using bqplot in Thebe, the pan/zoom button appears (with Font Awesome 4), but clicking the button does not allow the plot to be panned or zoomed.

Console output:
image

**To Reproduce**

Load the following HTML (or use this page: https://github.com/sandertyu/widgetstuffs/blob/8576956a999589f84d48024e5062c65cf70f58b4/Thebe/bqplot.html)
This is also the current documentation page for the bqplot example on Thebe: https://thebelab.readthedocs.io/en/latest/examples/bqplot_example.html
```
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" />
   <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"></script>
   <script type="text/x-thebe-config">
     {
       requestKernel: true,
       binderOptions: {
         repo: "bqplot/bqplot",
         ref: "0.12.18",
         binderUrl: "https://mybinder.org",
         repoProvider: "github",
       },
     }
   </script>
   <script src="https://unpkg.com/thebelab@latest/lib/index.js"></script>
   <button id="activateButton" style="width: 120px; height: 40px; font-size: 1.5em;">
     Activate
   </button>
   <script>
   var bootstrapThebe = function() {
       thebelab.bootstrap();
   }
   document.querySelector("#activateButton").addEventListener('click', bootstrapThebe)
   </script>
   <pre data-executable="true" data-language="python">
   import numpy as np
   from bqplot import pyplot as plt
   
   size = 100
   np.random.seed(0)
   x_data = np.arange(size)
   y_data = np.cumsum(np.random.randn(size)  * 100.0)
   
   plt.figure(title='My First Plot')
   plt.plot(x_data, y_data)
   plt.show()
   </pre>
```

**Environment**

- Python Version [e.g. 3.7.1]: 3.7.8
- Package versions or output of `jupyter-book --version`:
   bqplot: 0.12.18
- Operating System: Windows, Firefox

**Additional context**
This is an extension to #185.

### PR DESCRIPTION
**Pull request by celine168**
Intends to fix #302 

In this `_create_comm`, `this.kernel` returns undefined as the variable is never set. I set the variable in `registerWithKernel`. I also could not find the function `connectToComm` in the [KernelConnection](https://jupyterlab.github.io/jupyterlab/modules/_services_src_index_._services_src_kernel_kernel_.ikernelconnection.html#sendinputreply) class.
```
  _create_comm(target_name, model_id, data, metadata) {
    const comm = this.kernel.connectToComm(target_name, model_id);
    if (data || metdata) {
      comm.open(data, metadata);
    }
    return Promise.resolve(new ShimmedComm(comm));
  }
```

HTML page used to test:
```
<!DOCTYPE html>
<html>
    <head>
        <!-- Configure and load Thebe !-->
        <!-- two config sections: first binder, second local
        switch which one has type="text/x-thebe-config"
        to activate it
      -->
      <!-- script that allows the line plots to be displayed, otherwise it gives an error -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"></script>

      <!-- script for awesome fonts 4.0 needed for navigation buttons -->
      <script src="https://use.fontawesome.com/3e02a3c909.js"></script>

        <script type="text/x-thebe-config">
          {
            requestKernel: true,
            binderOptions: {
              repo: "bqplot/bqplot",
              ref: "0.12.18",
              codeMirrorConfig: {
                "theme": "abcdef"
              },
            },
          }
        </script>
        <!-- use this one (and set the token!) for local testing (much faster)
        e.g.
        jupyter notebook \
          --NotebookApp.token=thebe-test-secret \
          --NotebookApp.allow_origin='http://127.0.0.1:8080'
        -->
        <script type="text/x-thebe-config-disabled">
          {
            requestKernel: true,
            kernelOptions: {
              name: "python3",
              path: ".",
              // notebook server configuration; not needed with binder
              serverSettings: {
                "baseUrl": "http://127.0.0.1:8888",
                "token": "thebe-test-secret",
              },
            },
            codeMirrorConfig: {
              "theme": "abcdef"
            },
          }
        </script>
        <script src="./lib/index.js"></script>
    </head>
    <body>
        <div class="container">
            <button id="activateButton">Activate</button>
            <script>
                var bootstrapThebe = function() {
                    thebelab.bootstrap();
                }

                document.querySelector("#activateButton").addEventListener('click', bootstrapThebe)
            </script>

            <pre data-executable="true" data-language="python" class="pre-element">print("Hello!")</pre>
            <pre data-executable="true" data-language="python" class="pre-element">
from IPython.display import Math
Math("$x = 5$")
            </pre>
            <pre data-executable="true" data-language="python" class="pre-element">
import numpy as np
from bqplot import pyplot as plt

size = 100
np.random.seed(0)
x_data = np.arange(size)
y_data = np.cumsum(np.random.randn(size)  * 100.0)

plt.figure(title='My First Plot')
plt.plot(x_data, y_data)
plt.show()
            </pre>
        </div>
    </body>
    <style>
        body {
            margin: 0;
        }
        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        #activateButton {
            width: 130px;
            height: 50px;
            font-size: 1.25em;
            border: 1px solid black;
            border-radius: 5px;
            background-color: lightblue;
            text-transform: uppercase;
        }
        .pre-element {
            width: 50vw;
            height: 20vh;
            border: 2px solid #aaa;
            border-radius: 4px;
            margin-top: 8px;
            margin-bottom: 8px;
        }
        .thebelab-cell {
            width: 50vw;
        }
    </style>
</html>

```

### CODE REVIEW

**Comment by celine168** [comment]
@narrator0 and I just added a Jest test testing bqplot's pan/zoom button.

**Comment by moorepants** [comment]
Do other tests load a binder like this one? I worry that too much time is required to run the tests with that. But if others are doing that, I guess it is fine.

**Comment by celine168** [comment]
The [read-only test](https://github.com/executablebooks/thebe/blob/master/test/fixtures/HTML/readonly1.html) that was added does load binder but I believe it only checks whether [a specific tag exists](https://github.com/executablebooks/thebe/blob/master/test/readonly.test.js#L22). 

This test requires actually running the code block and testing whether the pan/zoom button will work without any error.

**Comment by Miniland1333** [comment]
Maybe wait on https://github.com/executablebooks/thebe/pull/282 to be merged in first

**Comment by stevejpurves** [comment]
@moorepants to your comment, plan is to soon have the test runner fire up a local jupyter server around the tests automatically making that connection fast. My plan was to do that once #282 is merged (or i'll extend that PR if it stays unmerged) as #282 has changes to the test layout it would be good to have that in first as @Miniland1333 suggests.

**Comment by moorepants** [comment]
@celine168 Can you update this to work with #282?

**Comment by celine168** [comment]
Just moved the files to the `e2e` directory! Hoping that works.

**Comment by celine168** [comment]
@stevejpurves @Miniland1333 Just checking, is it proper to move these tests to the `e2e` directory like this?

**Comment by moorepants** [comment]
We just reviewed this in our meeting and feel it is good to go. Merging.

**Comment by moorepants** [comment]
The tests were fine here but seem to be failing on master...

**Comment by moorepants** [comment]
I'm seeing:

```
PASS e2e/readonly.test.js
FAIL e2e/bqplot.test.js (32.212 s)
  ● Test bqplot › cells are default editable › case-bqplot-pan

    expect(received).resolves.toBeTruthy()

    Received promise rejected instead of resolved
    Rejected to value: [TimeoutError: waiting for selector `button.widget-toggle-button` failed: timeout 30000ms exceeded]

      45 |   describe("cells are default editable", () => {
      46 |     it("case-bqplot-pan", async () => {
    > 47 |       await expect(editBQPlot()).resolves.toBeTruthy();
         |             ^
      48 |     }, 100000000);
      49 |   });
      50 | });

      at expect (node_modules/expect/build/index.js:134:15)
      at Object.<anonymous>.global.expect (node_modules/expect-puppeteer/lib/index.js:118:12)
      at Object.<anonymous> (e2e/bqplot.test.js:47:13)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 16 passed, 17 total
Snapshots:   0 total
Time:        36.79 s
Ran all test suites matching /test.js/i.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! thebe@0.5.1 test:e2e: `jest test.js --config=./jest.e2e.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the thebe@0.5.1 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by moorepants** [comment]
Would this happen because binder takes too long to load?

**Comment by moorepants** [comment]
I opened #329 to revert, which I may do.

**Comment by moorepants** [comment]
I reverted the changes. I think we need to think more carefully about trying to run a binder in a js test. It isn't going to be reliable.

As I mentioned before, we need to test if the kernel attribute is present as expected, not check if bqplot runs properly. We can do that manually with the example in the docs.

**Comment by stevejpurves** [comment]
Can we reopen the original PR / branch?. I think we should bring up  the local test Jupyter server that was discussed, in order to reliably to connect to in this type of test. You can assign that one to me.

**Comment by celine168** [comment]
I apologize for suggesting merging this PR so early, especially considering the binder session in the jest test!

I have reopened the PR at #330!

**Pull request merged**
