### PR TITLE
temporarily disable dependabot

### PR DESCRIPTION
**Pull request by stevejpurves**
Proposal to temporarily disable dependabot and consider dependency upgrades in one go ahead of releases in a more structured way.

### CODE REVIEW

**Comment by stevejpurves** [comment]
@moorepants @choldgraf suggest we do this until we're ready for next release as @moorepants suggested

**Comment by moorepants** [comment]
Fine with me.

**Comment by choldgraf** [comment]
Is the plan to add it back in? If so then we should track this somewhere so we don't forget.

Maybe we can create an issue that gives at date where we should turn this back on or something? Or at the least add a comment in the code

In general I'm +1 on it, i trust y'all's judgment here

**Comment by stevejpurves** [comment]
I have opened #484 to track @choldgraf

**Pull request merged**
