### PR TITLE
[DOC] use the latest code in builds of the docs via GHA build

### PR DESCRIPTION
**Pull request by stevejpurves**
This PR aims to address #285 and change the default docs build to always use the version of `thebe` represented by the latest code in the repo. Previously the docs would load the latest published version from `unpkg`.

TODOS:

 - [x] add makefile commands to build the docs locally
 - [ ] update `readthedocs` builds as needed and ensure that these build with the latest local `thebe`

### CODE REVIEW

**Comment by stevejpurves** [comment]
@choldgraf I started afresh here as I was concentrating on the local build, but intend to pull over changes from https://github.com/executablebooks/thebe/pull/298 as needed to close this out.

**Comment by choldgraf** [comment]
Excellent! This will make it much easier to iterate. Is this ready for a review or do you wanna work on stuff further? I'd like to get this in ASAP

**Comment by stevejpurves** [comment]
@choldgraf I need to get the `readthedocs` task done but will prioritize that

**Comment by stevejpurves** [comment]
ok. Seems like there is no way to upgrade the node version on RTD even with the new `build.apt_packages` options.
This is a known issue and seems that it. is getting some attention here:

https://github.com/readthedocs/readthedocs-docker-images/issues/107

 As node is a dev dependency here, and I think we can use older versions ok. I've moved the engine requirement back to 8 and above to get this building until RTD updates their build system. I'm also leaving the current option file in place for now.

**Comment by stevejpurves** [comment]
ok, so pausing this on until RTD folks update their docker image and options :(

**Comment by stevejpurves** [comment]
Note: another way forward would be to use a github action to produce a local build on push, storing this as an artifact which the RTD build then consumes.

There is some good reference material in this repo https://github.com/dfm/rtds-action 

Taking over the thebe build and triggering the RTD build from this repo will give us full control over the JS build process. This seems like a good way to go! and one we can action asap.

**Comment by choldgraf** [comment]
@stevejpurves I'm +1 on using GitHub actions if it means that we get control over the JS environment that is needed to make progress here. I think that's a good enough reason to use GHA over readthedocs for now. If so, we should open an issue about switching back to RTD once the issue you've linked is resolved, and then switch the thebe docs to use GHA instead of RTD.

**Comment by stevejpurves** [comment]
@choldgraf great, let's try that. I'll need readthedocs access to setup the integration & have sent a message on EB slack 👍

**Comment by stevejpurves** [comment]
Note: this will hopefully be superseded by https://github.com/executablebooks/thebe/pull/472

**Comment by stevejpurves** [comment]
closing in favor of https://github.com/executablebooks/thebe/pull/472

**Pull request closed without merging**
