### PR TITLE
Add bqplot documentation

### PR DESCRIPTION
**Pull request by celine168**
image

### CODE REVIEW

**Comment by moorepants** [comment]
LGTM, merging as is.

**Comment by choldgraf** [comment]
fantastic! It worked great for me as well 👍

**Comment by moorepants** [comment]
I just tried it again and wasn't able to get the panzoom button to do anything. I clicked it, a blue edge appears around the button, and I'd expect that if I click, hold, and drag in the plot that it would pan, but nothing happens. Maybe I'm using the button wrong?

**Comment by celine168** [comment]
Ah yes, you are right. My bad on that, I didn't specifically test panning/zooming on the plot. 

I think there might be an underlying issue with this.

**Comment by celine168** [comment]
@moorepants @choldgraf would it be best practice for me to submit a PR reverting deleting the page before finding the fix?

**Comment by choldgraf** [comment]
I'd also be fine with adding a note about zoom not working, and opening an issue to track this problem.

**Pull request merged**
