### PR TITLE
Updated changelog with two fixes.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by choldgraf** [comment]
@moorepants do you think we should just make a release? Neither of those changes are breaking and seem to fix annoying UX problems

**Comment by moorepants** [comment]
I'm making it right now. And forgot about this PR in the process. I still can't figure out #382.

**Comment by moorepants** [comment]
The release worked, see: https://www.npmjs.com/package/thebe

**Comment by moorepants** [comment]
Sorry it was a bit messy. I was confounded by these npm dependency errors/warnings.

**Pull request closed without merging**
