### PR TITLE
request new kernel when kernel died

### PR DESCRIPTION
**Pull request by akhmerov**
Only handles the kernel part of #255

### CODE REVIEW

**Comment by choldgraf** [comment]
one quick thought here - is there some way for users to *know* that the kernel has been restarted? Perhaps we include a short warning message about it or something? Otherwise I fear folks will be confused when the state suddenly changes

**Comment by akhmerov** [comment]
So far this is largely useless and it's more about me figuring out where to put things.

**Comment by akhmerov** [comment]
As far as UI goes, there's going to be a message in the cell when the kernel is restarting. The problem I'm facing so far though is that a lot of functionality is only meant to be run once via bootstrap.

**Comment by akhmerov** [comment]
closing for now, I'll need to read up more on this.

**Pull request closed without merging**
