### PR TITLE
Integrate `thebe-core`

### PR DESCRIPTION
**Pull request by stevejpurves**
## Purpose

This PR will address #412 and #536 and in the process improve the build system. Changing the repo to be a `monorepo` will allow `thebe-core` to be built and published from here as well as making it easy to use it as a dependency in `thebe`. Once merged the `thebe-core` repo will be archived

## Tasks
 - [x] convert to a monorepo, ready to bring `thebe-core` in as a sub package
 - [x] upgrade the build system
 - [x] add `thebe-core`
 - [x] refactor thebe to use thebe core
    - [x] initial integration - cells are running
    - [x] change notebook interface (notebook should return an array of promises, one for each cell, return the cell id along with the each promise)
    - [x] fix busy spinners
    - [x] re-enable code complete
    - [x] Kernel Status
    - [x] ensure `events` system aligns with previous
    - [x] expose `verbose` events channel
    - [x] get docs building again
 - [x] setup eslint & prettier
 - [x] get demo app running with `thebe`, rather than `thebe-core`
 - [x] archive the `thebe-core` repo
 - [x] get juptyerlite working again, see: https://github.com/jupyterlite/jupyterlite/issues/864
 - [x] create `thebe-core` docs
    - [x] add docs on `thebe-lite`

### CODE REVIEW

**Comment by stevejpurves** [comment]
This PR is now ready for review and will go out in a release candidate. 

Note: the thebe docs for this branch are working, but the lack of immediate feedback on pressing activate is a current behavior change that we may want to review/revise - the lack of feedback is because the docs have not yet been updated to include anything to reflect the updated messaging available during connect. We should update the docs perhaps to include the thebe-status widget which will reflect this.

Also, we have not yet tested `sphinx-thebe` which we should do as soon as the `rc` is out

**Comment by stevejpurves** [comment]
ok this branch has been published as `v0.9.0-rc.0` with the `rc` tag on `npm`. This means the `@latest` via `unpkg.com` remains pointing to the latest stable release whilst `https://unpkg.com/thebe@rc/lib/index.js` can be used to load the release candidate.

Note: some speedbumps are to be expected when trying to switch, but it would be great to collaborate with some people who already have thebe integrations, for this rc -- initially just covering the basic features, before looking at enabling the jupyterlite option. cc @mmcky

**Comment by agoose77** [comment]
@stevejpurves this looks _very_ cool.

I'm interested in getting thebe with jupyterlite working with our docs over at https://github.com/scikit-hep/awkward, and from a first glance it seems like this *should* work? Do you have any example static folders that I can look at, so that I don't have to reverse engineer it? ;)

**Comment by agoose77** [comment]
@stevejpurves the default webpack configuration doesn't generate or serve a `_static` path. Do you have any hints as to what I need to add to support this?

**Comment by stevejpurves** [comment]
Tracking the jupyterlite issue in https://github.com/executablebooks/thebe/issues/560 but still no resolution :( 
I'm still thinking it is related to the bundling of `thebe` as `thebe-core` works bundled in the core demo.

**Comment by stevejpurves** [comment]
The remaining todos have been moved to issues #591 and #590.
Getting this into `main` will greatly help visibility and work towards `0.9.0`.
An `0.8.x` branch has been created for fixes to the current production version

**Comment by stevejpurves** [comment]
I have set the default on RTD to point to `stable` / `v0.8.2` at the moment.

**Pull request merged**
