### PR TITLE
📚 DOCS: add read-only docs

### PR DESCRIPTION
**Pull request by choldgraf**
follow-up to #274 

could @Miniland1333 or @moorepants confirm that these instructions are correct?

### CODE REVIEW

**Comment by moorepants** [comment]
LGTM

**Comment by choldgraf** [comment]
great, thanks!

**Comment by Miniland1333** [comment]
The only thing is that do you think we should mention the more specific use case of readOnly as default? If `{codeMirrorOptions:{readOnly:true }` is set in the Thebe config it makes cells readonly by default. Then, `data-readonly="false"` can be used to make certain cells explicitly editable. This is useful for my use case, but I had problems trying to document this without making it seem overly complex. This is also why I had to have extensive tests for such a relatively simple feature.

**Comment by choldgraf** [comment]
ah yes totally, I think it's a good idea to document how to enable this for all cells 👍 

want to make a PR giving it a shot and I'm happy to review?

**Comment by Miniland1333** [comment]
Continued in PR #287

**Pull request merged**
