### PR TITLE
[REF] convenience commands for testing against a local kernel

### PR DESCRIPTION
**Pull request by stevejpurves**
Problems this addresses:
 - Getting local development to work with a local kernel was not discoverable from the docs
 - switching to local changes required a code change to development.html, easy to commit in error

This PR aims to make it easier to chose to test against a local kernel without needing to change the code and improve discoverability.

Changes
 - moved single `development.html` to a folder and split to `local.html` and `binder.html` to cover the two cases
 - split out css to avoid repetition
 - added a note to the contributors guide
 - ensure previous `npm run develop` command works as before
 - added a `npm run develop:local` command to bring up the local page
 - added some instructions on how to start kernel on the local page

### CODE REVIEW

**Review by choldgraf — APPROVED** [review]
This seems good to me 👍 thanks for updating the documentation as well, agree it is much easier to run this locally and iterate more quickly

**Comment by moorepants** [comment]
LGTM too!

**Comment by stevejpurves** [comment]
thanks, I suggest we rebase this after getting #424 in which resolves the `package-lock.json` issue.

**Comment by stevejpurves** [comment]
@moorepants @choldgraf The lint issue is ongoing but being dealt with see #426 , it would be great to get this PR in ahead of Monday if possible :D

**Comment by moorepants** [comment]
@TimStewartJ, It would be great if you try out this PR. You can get some review practice in and help out @stevejpurves. I can also try this out too.

**Comment by TimStewartJ** [comment]
Yep, tried it out and it looks good to me as well!

**Review by choldgraf — APPROVED** [review]

**Comment by stevejpurves** [comment]
This one is now green ✅  on the lint stage too.
I resolved the conflicts with the updated `master` branch and this is ready to merge! 🥳

**Pull request merged**
